project:
  type: book
  output-dir: ../release/quarto

book:
  title: "Codex"
  author: "Carlos Nexans"
  language: es
  navbar:
    background: light
    search: true
  chapters:
    - index.md
    - 01_Logica.md
    - part: "Análisis Real"
      chapters:
        - 02_01_Analisis_Axiomas.md
        - 02_02_Analisis_Sucesiones.md
        - 02_03_Analisis_Limites.md
        - 02_04_Analisis_Herramientas.md
        - 02_05_Analisis_Derivadas.md
        - 02_06_Analisis_Integrales.md
    - part: "Variable Compleja"
      chapters:
        - 03_01_Variable_Compleja_Axiomas.md

filters:
  - callout-numbers.lua

format:
  html:
    theme: cosmo
    toc: true
    toc-location: left
    toc-depth: 2
    number-sections: false
    lang: es
    include-in-header: posthog.html
    css: custom.css
  pdf:
    pdf-engine: xelatex
    toc: true
    toc-depth: 2
    number-sections: false
    lang: es
    colorlinks: true
    urlcolor: cyan
    linkcolor: cyan
