project:
  type: book
  output-dir: ../release/quarto

book:
  title: "Codex"
  author: "Carlos Nexans"
  language: es
  navbar:
    background: light
    search: true
  chapters:
    - index.md
    - 02_Logica.md
    - part: "Análisis Real"
      chapters:
        - 03_Axiomas.md
        - 04_Sucesiones.md
        - 05_Limites.md
        - 06_Herramientas.md
        - 07_Derivadas.md
        - 08_Integrales.md

filters:
  - callout-numbers.lua

format:
  html:
    theme: cosmo
    toc: true
    toc-location: left
    toc-depth: 2
    number-sections: false
    lang: es
    include-in-header: posthog.html
    css: custom.css
  pdf:
    pdf-engine: xelatex
    toc: true
    toc-depth: 2
    number-sections: false
    lang: es
    colorlinks: true
    urlcolor: cyan
    linkcolor: cyan
